services:
  drug-api:
    build: .
    container_name: drug_api_server
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./results:/app/results
      - ./models:/app/models
    restart: unless-stopped
